[phases.setup]
nixpkgs = [
  "python310",
  "pip",
  "postgresql",
  "gcc",
  "pkg-config",
  "libsasl",
  "openldap.dev",    # ✅ ajoute les headers manquants comme lber.h
  "libldap",          # ✅ optionnel, pour les bindings
  "cyrus_sasl"        # ✅ parfois requis pour la compilation avec SASL
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && ./odoo-bin -d $DB_NAME -r $DB_USER -w $DB_PASSWORD --addons-path=addons --db_host=$DB_HOST --db_port=$DB_PORT --http-port=8000"
