[phases.setup]
nixpkgs = [
  "python310",
  "pip",
  "gcc",
  "pkg-config",
  "libsasl",
  "openldap.dev",    # ✅ contient lber.h et ldap.h
  "libldap",
  "cyrus_sasl",
  "postgresql"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && ./odoo-bin -d $DB_NAME -r $DB_USER -w $DB_PASSWORD --addons-path=addons --db_host=$DB_HOST --db_port=$DB_PORT --http-port=8080"
