[phases.setup]
nixpkgs = [
  "python310",
  "pip",
  "gcc",
  "pkg-config",
  "libsasl",
  "openldap.dev",    # ⚠️ très important : contient lber.h
  "libldap",
  "cyrus_sasl",
  "postgresql"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && python ./odoo-bin --db_host=$DB_HOST --db_port=$DB_PORT --db_user=$DB_USER --db_password=$DB_PASSWORD -d $DB_NAME --addons-path=addons --http-port=8080"
