services:
  - type: web
    name: odoo18-docker
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: PGHOST
        sync: false
      - key: PGPORT
        value: "5432"
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGDATABASE
        sync: false
