services:
  - type: web
    name: odoo18
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: >
      ./odoo-bin --addons-path=addons
      --db_host=$PGHOST --db_port=$PGPORT --db_user=$PGUSER
      --db_password=$PGPASSWORD --db_name=$PGDATABASE
      --xmlrpc-port=$PORT --log-level=info
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: WORKERS
        value: "0"
    runtime: python
    pythonVersion: 3.10
